In [1]:
print("hello WOrld")

hello WOrld


In [22]:
string1 = input("Press Enter to continue...: ")
list1 = []
for char in string1:
    list1.append(int(char))

In [25]:
string1

'1010101'

In [26]:
list1

[1, 0, 1, 0, 1, 0, 1]

In [28]:
def string_bits_to_list(string1):
    list1 = []
    for char in string1:
        list1.append(int(char))
    return list1

In [29]:
string_bits_to_list("1010101")

[1, 0, 1, 0, 1, 0, 1]

In [30]:
def bitify(string1):
    return (string_bits_to_list(string1))

In [31]:
bitify("1010101")

[1, 0, 1, 0, 1, 0, 1]

In [1]:
import pandas as pd
import numpy as np

In [18]:
bits = np.random.randint(0, 2, size=16, dtype=int)

In [19]:
bits

array([0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0], dtype=int32)

In [20]:
bits[[2**i for i in range(4)]]

array([0, 1, 1, 1], dtype=int32)

In [ ]:
if [(2**i)= for i in range(4)]:
    print("hello")

In [76]:
mystr = ["0","0","0","0"]
for i in range(16):
    list2.append("".join(mystr))
    for j in range(3,-1,-1):
        if mystr[j]=="0":   
            mystr[j] = '1'
            break
        elif mystr[j]=="1":
            mystr[j] = "0"

In [91]:
def print_binarys(bits):
    bitlist = ["0"]*bits
    for i in range(2**bits):
        print("".join(bitlist))
        for j in range(bits-1,-1,-1):
            if bitlist[j] == "0":
                bitlist[j] = "1"
                break
            elif bitlist[j] == "1":
                bitlist[j] = "0"


In [94]:
print_binarys(3)

000
001
010
011
100
101
110
111


In [77]:
list2

['0000',
 '0001',
 '0010',
 '0011',
 '0100',
 '0101',
 '0110',
 '0111',
 '1000',
 '1001',
 '1010',
 '1011',
 '1100',
 '1101',
 '1110',
 '1111']

In [59]:
S=["0","0","0","0"]
str1 = []
for i in range(16):
    str1.append("".join(S))
    for j in range(3,-1,-1):
        if S[j]=="0":
            S[j]="1"
            break
        elif S[j]=="1":
            S[j]="0"

In [60]:
str1

['0000',
 '0001',
 '0010',
 '0011',
 '0100',
 '0101',
 '0110',
 '0111',
 '1000',
 '1001',
 '1010',
 '1011',
 '1100',
 '1101',
 '1110',
 '1111']

In [80]:
list3 = list(bits)

In [81]:
list3

[np.int32(0),
 np.int32(0),
 np.int32(1),
 np.int32(0),
 np.int32(1),
 np.int32(1),
 np.int32(0),
 np.int32(0),
 np.int32(1),
 np.int32(1),
 np.int32(1),
 np.int32(1),
 np.int32(1),
 np.int32(0),
 np.int32(0),
 np.int32(0)]

In [82]:
list4 = []
for bit in bits:
    list4.append(int(bit))

In [83]:
list4

[0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0]

In [87]:
list5 = []

In [88]:
for i in range(16):
    list5.append((list4[i], list2[i]))

In [89]:
list5

[(0, '0000'),
 (0, '0001'),
 (1, '0010'),
 (0, '0011'),
 (1, '0100'),
 (1, '0101'),
 (0, '0110'),
 (0, '0111'),
 (1, '1000'),
 (1, '1001'),
 (1, '1010'),
 (1, '1011'),
 (1, '1100'),
 (0, '1101'),
 (0, '1110'),
 (0, '1111')]

In [95]:
nparray = np.array(list5)

In [134]:
nparray

array([['0', '0000'],
       ['0', '0001'],
       ['1', '0010'],
       ['0', '0011'],
       ['1', '0100'],
       ['1', '0101'],
       ['0', '0110'],
       ['0', '0111'],
       ['1', '1000'],
       ['1', '1001'],
       ['1', '1010'],
       ['1', '1011'],
       ['1', '1100'],
       ['0', '1101'],
       ['0', '1110'],
       ['0', '1111']], dtype='<U21')

In [121]:
nparray[nparray[:, 0] == '1'][:, 1]

array(['0010', '0100', '0101', '1000', '1001', '1010', '1011', '1100'],
      dtype='<U21')

In [123]:
nparray[nparray[:, 0] == '1']

array([['1', '0010'],
       ['1', '0100'],
       ['1', '0101'],
       ['1', '1000'],
       ['1', '1001'],
       ['1', '1010'],
       ['1', '1011'],
       ['1', '1100']], dtype='<U21')

In [143]:
j = 1  # index you want
nparray[(nparray[:, 0] == '1') & np.char.endswith(nparray[:, 1], "1")]


array([['1', '0101'],
       ['1', '1001'],
       ['1', '1011']], dtype='<U21')

In [139]:
nparray[:, 1][0][-1] == "0"

True

In [148]:
import numpy as np

def filter_by_bit(nparray, bit_index, bit_value="1"):
    """
    bit_index:
        0 = first bit
        -1 = last bit
        positive or negative indices allowed
    bit_value:
        "0" or "1"
    """
    # Extract the bit at the given index for all rows
    bits = np.array([row[1][bit_index] for row in nparray])

    # Build mask
    mask = (nparray[:, 0] == '1') & (bits == bit_value)

    return nparray[mask]

for bit_index in range(len(nparray[0, 1])):
    filtered = filter_by_bit(nparray, bit_index, "1")
    print("Bit index", bit_index, ":")
    for i in filtered:
        print(i)


Bit index 0 :
['1' '1000']
['1' '1001']
['1' '1010']
['1' '1011']
['1' '1100']
Bit index 1 :
['1' '0100']
['1' '0101']
['1' '1100']
Bit index 2 :
['1' '0010']
['1' '1010']
['1' '1011']
Bit index 3 :
['1' '0101']
['1' '1001']
['1' '1011']


In [152]:
print( 7 ^ 8)

15


In [154]:
nparray[nparray[:, 0] == '1'][:,1]

array(['0010', '0100', '0101', '1000', '1001', '1010', '1011', '1100'],
      dtype='<U21')

<hr>

In [177]:
bits[7]= not bits[7]

In [165]:
bits = np.random.randint(0,2,16,dtype=int)
print(bits)

[1 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0]


In [178]:
bits

array([1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int32)

In [179]:
bits_list = list(enumerate(bits))
print(bits_list)

[(0, np.int32(1)), (1, np.int32(0)), (2, np.int32(0)), (3, np.int32(1)), (4, np.int32(0)), (5, np.int32(0)), (6, np.int32(0)), (7, np.int32(1)), (8, np.int32(1)), (9, np.int32(0)), (10, np.int32(0)), (11, np.int32(0)), (12, np.int32(1)), (13, np.int32(0)), (14, np.int32(0)), (15, np.int32(0))]


In [180]:
xor = [i for i,bit in bits_list if bit]

In [181]:
xor

[0, 3, 7, 8, 12]

In [182]:
parity = 0
for i in xor:
    parity = parity ^ i

In [183]:
parity

0

In [184]:
def calculate_parity(bits):
    bits_list = list(enumerate(bits))
    xor = [i for i,bit in bits_list if bit]
    parity = 0
    for i in xor:
        parity = parity ^ i
    return parity
calculate_parity(bits)

0

In [ ]:
reduce(lambda x,y: x ^ y, [i for i,bit in enumerate(bits) if bit])

SyntaxError: invalid syntax (3577089919.py, line 1)

In [202]:
i = 5  #index of changed bit
bits[i] = not bits[i]

In [ ]:
##reduce
bits_list = list(enumerate(bits))
xor = [i for i,bit in bits_list if bit]
parity = 0
for i in xor:
    parity = parity ^ i
print(parity) #Displays Index of Changed bit through Parity Calculations
# 0 means no bits changed

0
